"""System prompts for all agents."""

from hdx_agent.prompts.templates import (
    INTENT_DETECTION_PROMPT,
    REACT_SYSTEM_PROMPT,
    SQL_EXPLAIN_PROMPT,
    ERROR_EXPLAIN_PROMPT,
    SQL_FIX_PROMPT,
    CLARIFICATION_PROMPT,
)

__all__ = [
    "INTENT_DETECTION_PROMPT",
    "REACT_SYSTEM_PROMPT",
    "SQL_EXPLAIN_PROMPT",
    "ERROR_EXPLAIN_PROMPT",
    "SQL_FIX_PROMPT",
    "CLARIFICATION_PROMPT",
]
